name: Deploy app

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: npm ci
        run: npm ci
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        run: npm test
      - name: deploy on github pages
        run: npm run deploy
      